
import { Provider } from "react-redux";
import "./globals.css";
import QueryProvider from "./QueryProvider";
import ReduxProvider from "./store/ReduxProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <QueryProvider>
            <main>
              {children}
            </main>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
